/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;


import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tec
 */
public final class TCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TCadastro
     */
    public TCadastro() {
        
        initComponents();
        data.setText(new SimpleDateFormat("YYYY-MM-d").format(new Date(System.currentTimeMillis())));
        data.setEditable(false);
        data.setEnabled(false);
        pesquisar();
        preencherTabela();
        GeradorDeCodigoMaterial();
        mat_cod.setEditable(false);
        GeradorDeCodigoFornecedior();
        fornc_cod.setEditable(false);
        ListadeFornecedores();
       
        
        
    }
  String url = "jdbc:mysql://localhost:3308/sgs";
  String driver ="com.mysql.jdbc.Driver";
  String usuario = "root";
  String senha ="1234";
  Connection con;
  ResultSet rs = null;
    //select mat_cod as Código_Material, mat_descricao as Descrição, fornec_preco as Preço, fornec_data as Data_do_Fornecimento, for_nome as Fornecedor from material inner join fornecimento on mat_cod=cod_mat inner join fornecedor on for_cod=cod_for;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        mat_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mat_desc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        fornc_cod = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fornecedores = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        fornc_quantidade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        forn_preco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaMaterial = new javax.swing.JTable();
        conbpesquisa = new javax.swing.JComboBox();
        txpesquisar = new javax.swing.JTextField();
        jbtpesqui = new javax.swing.JButton();

        setClosable(true);
        setForeground(java.awt.Color.lightGray);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("CADASTRAR MATERIAL");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Material"));

        jLabel1.setText("CODIGO");

        mat_cod.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mat_cod.setText("  ");
        mat_cod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mat_codActionPerformed(evt);
            }
        });

        jLabel2.setText("DESCRIÇÃO MATERIAL");

        mat_desc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(mat_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mat_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mat_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mat_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecimento"));

        jLabel3.setText("CODIGO");

        jLabel4.setText("CODIGO DO FORNECEDOR");

        fornecedores.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "15", "25", "78", "1" }));

        jLabel5.setText("QUANTIDADES");

        jLabel6.setText("PREÇO");

        forn_preco.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jLabel7.setText("MT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(fornc_quantidade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fornc_cod, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fornecedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(forn_preco, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(data)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornc_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fornc_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forn_preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jButton1.setText("CADASTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar Material"));

        tabelaMaterial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaMaterial);

        conbpesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Todos", "Buscar por Codigo", "Buscar por Nome" }));
        conbpesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                conbpesquisaItemStateChanged(evt);
            }
        });

        txpesquisar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jbtpesqui.setText("Pesquisar");
        jbtpesqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtpesquiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(conbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbtpesqui)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtpesqui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "INSERT INTO material (mat_cod, mat_descricao) VALUES( ?,? )";
            PreparedStatement stmt = con.prepareStatement(sql);
             // Prepare a statement to insert a record  
        
        stmt.setString(1,mat_cod.getText());
        stmt.setString(2,mat_desc.getText());
      
         
             stmt.execute();  
              
            // Execute the insert statement  
        stmt.executeUpdate(sql);
        stmt.close();
        } catch (SQLException ex) {
          //caso haja um erro não sera passado nada
        }
   try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "INSERT INTO fornecimento  VALUES( ?,?,?,?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
             // Prepare a statement to insert a record  
        
        stmt.setString(1,fornc_cod.getText());
        stmt.setString(2, (String) fornecedores.getSelectedItem());
        stmt.setString(3, mat_cod.getText());
        stmt.setString(4,fornc_quantidade.getText());
        stmt.setString(5,forn_preco.getText());
        stmt.setString(6,data.getText());
            
             stmt.execute();  
              
            // Execute the insert statement  
        stmt.executeUpdate(sql);
        stmt.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Salvo com sucesso...");
  
        }
        Limpar();
        preencherTabela();
        GeradorDeCodigoMaterial();
        GeradorDeCodigoFornecedior();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       Limpar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void conbpesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_conbpesquisaItemStateChanged
    txpesquisar.setText(null);
    
    }//GEN-LAST:event_conbpesquisaItemStateChanged

    private void jbtpesquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtpesquiActionPerformed
       preencherTabela();
    }//GEN-LAST:event_jbtpesquiActionPerformed

    private void mat_codActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mat_codActionPerformed
     
    }//GEN-LAST:event_mat_codActionPerformed
public void Limpar(){
           // fornc_cod.setText(null);
           // mat_cod.setText(null);
            forn_preco.setText(null);
            mat_desc.setText(null);
            fornc_quantidade.setText(null);
}


 public void pesquisar(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select mat_cod as Código_Material, mat_descricao as Descrição, fornec_preco as Preço, fornec_data as Data_do_Fornecimento, for_nome as Fornecedor from material inner join fornecimento on mat_cod=cod_mat inner join fornecedor on for_cod=cod_for ";
            PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             tabelaMaterial.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();  
        stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
  public void pesquisarCodigo(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select mat_cod as Código_Material, mat_descricao as Descrição, fornec_preco as Preço, fornec_data as Data_do_Fornecimento, for_nome as Fornecedor from material inner join fornecimento on mat_cod=cod_mat inner join fornecedor on for_cod=cod_for where mat_cod like ?; ";
            PreparedStatement stmt = con.prepareStatement(sql);
             stmt.setString(1, txpesquisar.getText());
             rs = stmt.executeQuery();
             tabelaMaterial.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();   
       
        stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
  
  public void pesquisarNome(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select mat_cod as Código_Material, mat_descricao as Descrição, fornec_preco as Preço, fornec_data as Data_do_Fornecimento, for_nome as Fornecedor from material inner join fornecimento on mat_cod=cod_mat inner join fornecedor on for_cod=cod_for where mat_descricao like ? ";
            PreparedStatement stmt = con.prepareStatement(sql);
             stmt.setString(1, txpesquisar.getText());
             rs = stmt.executeQuery();
             tabelaMaterial.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();   
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
   public void preencherTabela() {
        try {
            if (conbpesquisa.getSelectedIndex() == 0) {
                pesquisar();
            } else if (conbpesquisa.getSelectedIndex() == 1) {
                pesquisarCodigo();
            } else if (conbpesquisa.getSelectedIndex() == 2) {
                pesquisarNome();   
            }
        } catch (Exception e) {  
        }
   }
   
   public void GeradorDeCodigoMaterial() {
         try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select max(mat_cod) from material;";
           PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             int somatorio = 1;
              while(rs.next()) {
   
                  // retornar o valor num textfield
                  somatorio = somatorio+rs.getInt(1);
                  mat_cod.setText(String.valueOf(somatorio));
                    
                             
              }
             stmt.execute();  
           
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }

 
   }
   
   public void GeradorDeCodigoFornecedior() {
         try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select max(fornec_cod) from fornecimento";
           PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             int somatorio = 1;
              while(rs.next()) {
   
                  // retornar o valor num textfield
                  somatorio = somatorio+rs.getInt(1);
                  fornc_cod.setText(String.valueOf(somatorio));
                    
                             
              }
             stmt.execute();  
           
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
   }
   
   public void ListadeFornecedores(){
       try {
           List<String> list = new ArrayList<String>();
          
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = " select for_cod, for_nome from fornecedor";
           PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
              while(rs.next()) {
   
                 list.add(rs.getString(1));
             
                             
              }
             stmt.execute();  
           
        stmt.close();
        
        //Instanciando o DefaultComboBoxModel
        DefaultComboBoxModel defaultComboBox = new DefaultComboBoxModel(list.toArray());
        //passando os valores do "modelo" pro ComboBox
        fornecedores.setModel(defaultComboBox);
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
       
   }
   
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox conbpesquisa;
    private javax.swing.JTextField data;
    private javax.swing.JTextField forn_preco;
    private javax.swing.JTextField fornc_cod;
    private javax.swing.JTextField fornc_quantidade;
    private javax.swing.JComboBox fornecedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtpesqui;
    private javax.swing.JTextField mat_cod;
    private javax.swing.JTextField mat_desc;
    private javax.swing.JTable tabelaMaterial;
    private javax.swing.JTextField txpesquisar;
    // End of variables declaration//GEN-END:variables
}
