/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Tec
 */
public class TCliente extends javax.swing.JInternalFrame {
  String url = "jdbc:mysql://localhost:3308/sgs";
  String driver ="com.mysql.jdbc.Driver";
  String usuario = "root";
  String senha ="1234";
  Connection con;
  ResultSet rs = null;
    /**
     * Creates new form TCliente
     */
    public TCliente() {
        initComponents();
        GeradorDeCodigoCliente();
        pesquisar();
        codCliente.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        clinome = new javax.swing.JTextField();
        nuit = new javax.swing.JTextField();
        telef = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        codCliente = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabClientes = new javax.swing.JTable();
        conbpesquisa = new javax.swing.JComboBox();
        txpesquisar = new javax.swing.JTextField();
        jbtpesqui = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Clientes"));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastrar Cliente"));

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Apagar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cliente");

        clinome.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Telefone");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nuit");

        jButton1.setText("Editar");

        codCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nuit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(telef)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(jButton2))
                        .addComponent(jLabel1)
                        .addComponent(clinome, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(codCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(codCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clinome, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("CLIENT");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes Cadastrados"));

        tabClientes.setBackground(new java.awt.Color(204, 255, 255));
        tabClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabClientes);

        conbpesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Todos", "Buscar por Codigo", "Buscar por Nome" }));
        conbpesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                conbpesquisaItemStateChanged(evt);
            }
        });

        txpesquisar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jbtpesqui.setText("Pesquisar");
        jbtpesqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtpesquiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(conbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbtpesqui, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtpesqui))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cadastroCliente();
        LimparCampos();
        GeradorDeCodigoCliente();
            preencherTabela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void conbpesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_conbpesquisaItemStateChanged
        txpesquisar.setText(null);

    }//GEN-LAST:event_conbpesquisaItemStateChanged

    private void jbtpesquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtpesquiActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jbtpesquiActionPerformed
public void LimparCampos(){
    telef.setText(null);
    clinome.setText(null);
    nuit.setText(null);
  
}
public void GeradorDeCodigoCliente() {
         try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select max(cliente_cod) from cliente;";
           PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             int somatorio = 1;
              while(rs.next()) {
   
                  // retornar o valor num textfield
                  somatorio = somatorio+rs.getInt(1);
                  codCliente.setText(String.valueOf(somatorio));
                    
                             
              }
             stmt.execute();  
           
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
   }
 public void pesquisar(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select Cliente_cod as Código, Cliente_nome as Nome, Cliente_nuit as NUIT, telef as Telefone from cliente inner join clientetelef on Cliente_cod =cod_cliente";
            PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             tabClientes.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();  
        stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
  public void pesquisarCodigo(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select Cliente_cod as Código, Cliente_nome as Nome, Cliente_nuit as NUIT, telef as Telefone from cliente inner join clientetelef on Cliente_cod =cod_cliente where cliente_cod like ?";
            PreparedStatement stmt = con.prepareStatement(sql);
             stmt.setString(1, txpesquisar.getText());
             rs = stmt.executeQuery();
             tabClientes.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();   
       
        stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
  
  public void pesquisarNome(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select Cliente_cod as Código, Cliente_nome as Nome, Cliente_nuit as NUIT, telef as Telefone from cliente inner join clientetelef on Cliente_cod =cod_cliente where cliente_nome like ?";
            PreparedStatement stmt = con.prepareStatement(sql);
             stmt.setString(1, txpesquisar.getText()+"%");
             rs = stmt.executeQuery();
             tabClientes.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();   
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
   public void preencherTabela() {
        try {
            if (conbpesquisa.getSelectedIndex() == 0) {
                pesquisar();
            } else if (conbpesquisa.getSelectedIndex() == 1) {
                pesquisarCodigo();
            } else if (conbpesquisa.getSelectedIndex() == 2) {
                pesquisarNome();   
            }
        } catch (Exception e) {  
        }
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField clinome;
    private javax.swing.JTextField codCliente;
    private javax.swing.JComboBox conbpesquisa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtpesqui;
    private javax.swing.JTextField nuit;
    private javax.swing.JTable tabClientes;
    private javax.swing.JTextField telef;
    private javax.swing.JTextField txpesquisar;
    // End of variables declaration//GEN-END:variables

    private void cadastroCliente() {
        try{
      System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "insert into cliente(cliente_cod,cliente_nome,cliente_nuit) values(?,?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1,codCliente.getText());
        stmt.setString(2,clinome.getText());
         stmt.setString(3,nuit.getText());
         stmt.execute();    
        stmt.executeUpdate(sql);
        stmt.close();
        } catch (SQLException ex) {
         // JOptionPane.showMessageDialog(null, "Algo Esta errado "+ex,"Erro",JOptionPane.ERROR_MESSAGE);
        }
        
        try{
      System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "insert into clientetelef(cod_cliente,telef) values(?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1,codCliente.getText());
            stmt.setString(2,telef.getText());
             stmt.execute();    
            stmt.executeUpdate(sql);
            stmt.close();
            } catch (SQLException ex) {
                //JOptionPane.showMessageDialog(null, "Algo Esta errado "+ex,"Erro",JOptionPane.ERROR_MESSAGE);
            }
    }
}



