/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



/**
 *
 * @author Tec
 */
public class TFornecedores extends javax.swing.JInternalFrame {
 String url = "jdbc:mysql://localhost:3308/sgs";
 String driver ="com.mysql.jdbc.Driver";
 String usuario = "root";
 String senha ="1234";
 Connection con;
  ResultSet rs = null;
  
    /**
     * Creates new form TFornecedores
     */
    public TFornecedores() {
        initComponents();
       pesquisar();
     for_cod.setEditable(false);
     GeradorDeCodigoFornecedor();
 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        for_cod = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        for_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        for_end = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        for_tel = new javax.swing.JTextField();
        for_telef2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        conbpesquisa = new javax.swing.JComboBox();
        txpesquisar = new javax.swing.JTextField();
        jbtpesqui = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("CADASTRAR FORNECEDORES");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedor"));

        jLabel1.setText("CODIGO");

        jLabel2.setText("NOME");

        jLabel3.setText("ENDEREÇO");

        jLabel4.setText("TELEFONES");

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(61, 61, 61)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(for_tel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(for_telef2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(for_end))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(for_cod, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(160, 160, 160)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(for_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_cod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(for_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_end, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(for_telef2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jt1);

        conbpesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Buscar Todos", "Buscar por Codigo", "Buscar por Nome" }));
        conbpesquisa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                conbpesquisaItemStateChanged(evt);
            }
        });

        txpesquisar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jbtpesqui.setText("Pesquisar");
        jbtpesqui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtpesquiActionPerformed(evt);
            }
        });

        jButton2.setText("Editar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE))
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(conbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jbtpesqui)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(conbpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtpesqui)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
  try {
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "INSERT INTO fornecedor VALUES( ?,?,? )";
            PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1,for_cod.getText());
        stmt.setString(2,for_nome.getText());
        stmt.setString(3,for_end.getText());     
        stmt.execute();  
        stmt.executeUpdate(sql);
        stmt.close();
        } catch (SQLException ex) {
        }
  
  try {
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "INSERT INTO fornecedortelef VALUES( ?,?),(?,?)";
            PreparedStatement stmt = con.prepareStatement(sql);
        stmt.setString(1,for_cod.getText());
        stmt.setString(2,for_telef2.getText());
        stmt.setString(3,for_cod.getText());
        stmt.setString(4,for_tel.getText());
        stmt.execute();  
        stmt.executeUpdate(sql);
        stmt.close();
        } catch (SQLException ex) {
           
        }
             JOptionPane.showMessageDialog(null,"Guardado");
             pesquisar();
             Limpar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    Limpar();       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void conbpesquisaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_conbpesquisaItemStateChanged
        txpesquisar.setText(null);

    }//GEN-LAST:event_conbpesquisaItemStateChanged

    private void jbtpesquiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtpesquiActionPerformed
        preencherTabela();
    }//GEN-LAST:event_jbtpesquiActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
    }//GEN-LAST:event_jButton2ActionPerformed
public void Limpar(){
    //for_cod.setText(null);
    for_end.setText(null);
    for_tel.setText(null);
    for_telef2.setText(null);
    for_nome.setText(null);
}
public void pesquisar(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select for_cod as Codigo,for_nome as Fornecedor, endereco as Endereço, telef as Contacto from fornecedor inner join fornecedortelef on for_cod = cod_for";
            PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             jt1.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();  
        stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
 public void pesquisarCodigo(){
  try {
         
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select for_cod as Codigo,for_nome as Fornecedor, endereco as Endereço, telef as Contacto from fornecedor inner join fornecedortelef on for_cod = cod_for where for_cod =? ";
            PreparedStatement stmt = con.prepareStatement(sql);
             stmt.setString(1, txpesquisar.getText());
             rs = stmt.executeQuery();
             jt1.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();   
       
        stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
  
  public void pesquisarNome(){
  try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select for_cod as Codigo,for_nome as Fornecedor, endereco as Endereço, telef as Contacto from fornecedor inner join fornecedortelef on for_cod = cod_for where for_nome like ? ";
            PreparedStatement stmt = con.prepareStatement(sql);
             stmt.setString(1, txpesquisar.getText()+"%");
             rs = stmt.executeQuery();
             jt1.setModel(DbUtils.resultSetToTableModel(rs));
             stmt.execute();   
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
   public void preencherTabela() {
        try {
            if (conbpesquisa.getSelectedIndex() == 0) {
                pesquisar();
            } else if (conbpesquisa.getSelectedIndex() == 1) {
                pesquisarCodigo();
            } else if (conbpesquisa.getSelectedIndex() == 2) {
                pesquisarNome();   
            }
        } catch (Exception e) {  
        }
   }
    public void Editar(){
  try {
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
            String sql = "select for_cod as Codigo,for_nome as Fornecedor, endereco as Endereço, telef as Contacto from fornecedor inner join fornecedortelef on for_cod = cod_for where for_nome like ? ";
            PreparedStatement stmt = con.prepareStatement(sql);
            stmt.setString(1, txpesquisar.getText()+"%");
            rs = stmt.executeQuery();
            jt1.setModel(DbUtils.resultSetToTableModel(rs));
            stmt.execute();   
            stmt.close();
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
    }
       public void GeradorDeCodigoFornecedor() {
         try {
            System.setProperty("jdbc.driver", driver);
            con = (Connection) DriverManager.getConnection(url,usuario,senha);
           String sql = "select max(for_cod) from fornecedor";
           PreparedStatement stmt = con.prepareStatement(sql);
             rs = stmt.executeQuery();
             int somatorio = 1;
              while(rs.next()) {
   
                  // retornar o valor num textfield
                  somatorio = somatorio+rs.getInt(1);
                  for_cod.setText(String.valueOf(somatorio));           
              }
             stmt.execute();  
           
        stmt.close();
       
        } catch (SQLException ex) {
          JOptionPane.showMessageDialog(null, ex);
        }
   }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox conbpesquisa;
    private javax.swing.JTextField for_cod;
    private javax.swing.JTextField for_end;
    private javax.swing.JTextField for_nome;
    private javax.swing.JTextField for_tel;
    private javax.swing.JTextField for_telef2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtpesqui;
    private javax.swing.JTable jt1;
    private javax.swing.JTextField txpesquisar;
    // End of variables declaration//GEN-END:variables

   
}
